/**
 * Postman v2.1 is the interchange format users share collections in, so an
 * export must be able to come back without quietly dropping parts of a request.
 * Ids are regenerated by design (imported items are new objects), everything
 * else is compared field by field.
 */
import { describe, expect, it } from 'vitest'
import { exportPostmanCollection, importPostmanCollection } from './postman'
import type { CollectionFolderNode, CollectionNode, RequestModel } from '@shared/types'

/** Drop generated ids so two trees can be compared structurally. */
function strip(node: CollectionNode): unknown {
  if (node.type === 'request') {
    const { id: _id, examples, ...rest } = node.request
    return {
      type: 'request',
      request: { ...rest, examples: examples?.map(({ id: _exId, ...ex }) => ex) }
    }
  }
  const { id: _id, children, variables, ...rest } = node
  return {
    ...rest,
    variables: variables?.map(({ id: _varId, ...v }) => v),
    children: children.map(strip)
  }
}

function req(over: Partial<RequestModel> = {}): RequestModel {
  return {
    id: 'r1',
    name: 'Create item',
    method: 'POST',
    url: 'https://api.example.com/items/:id',
    query: [
      { key: 'verbose', value: 'true', enabled: true, description: 'more output' },
      { key: 'off', value: '1', enabled: false }
    ],
    headers: [
      { key: 'X-Api', value: 'v2', enabled: true, description: 'API version' },
      { key: 'X-Off', value: '0', enabled: false }
    ],
    pathVariables: [{ key: 'id', value: '42', enabled: true, description: 'item id' }],
    body: { type: 'raw', language: 'json', text: '{"a":1}' },
    auth: { type: 'bearer', token: 'abc' },
    description: 'Request description',
    ...over
  }
}

function sample(): CollectionFolderNode {
  return {
    id: 'col',
    type: 'collection',
    name: 'Shop API',
    description: 'Collection description',
    auth: { type: 'basic', username: 'u', password: 'p' },
    variables: [
      { key: 'base', value: 'https://api.example.com', enabled: true },
      { key: 'legacy', value: 'off', enabled: false }
    ],
    preRequestScript: 'console.log("pre")',
    testScript: 'pm.test("ok", () => {})',
    children: [
      {
        id: 'f1',
        type: 'folder',
        name: 'Items',
        description: 'Folder description',
        auth: { type: 'apikey', key: 'X-Key', value: 'secret', addTo: 'header' },
        preRequestScript: 'console.log("folder pre")',
        testScript: 'console.log("folder test")',
        children: [
          { id: 'r1', type: 'request', request: req() },
          {
            id: 'r2',
            type: 'request',
            request: req({
              name: 'Form',
              body: {
                type: 'urlencoded',
                items: [
                  { key: 'a', value: '1', enabled: true, description: 'first' },
                  { key: 'b', value: '2', enabled: false }
                ]
              },
              auth: { type: 'none' }
            })
          },
          {
            id: 'r3',
            type: 'request',
            request: req({
              name: 'Multipart',
              body: {
                type: 'formdata',
                items: [
                  { key: 'text', type: 'text', value: 'значение', enabled: true },
                  { key: 'file', type: 'file', value: '', filePath: '/tmp/a.png', contentType: 'image/png', enabled: false }
                ]
              },
              auth: { type: 'digest', username: 'du', password: 'dp' }
            })
          },
          {
            id: 'r4',
            type: 'request',
            request: req({
              name: 'GraphQL',
              body: { type: 'graphql', query: 'query { me { id } }', variables: '{"x":1}' },
              auth: { type: 'none' }
            })
          },
          {
            id: 'r5',
            type: 'request',
            request: req({
              name: 'Scripts and examples',
              body: { type: 'none' },
              auth: { type: 'none' },
              preRequestScript: 'const a = 1\nconst b = 2',
              testScript: 'pm.test("x", () => {})',
              examples: [
                {
                  id: 'ex1',
                  name: 'Created',
                  status: 201,
                  headers: [['content-type', 'application/json']],
                  body: '{"ok":true}',
                  contentType: 'application/json'
                }
              ]
            })
          }
        ]
      }
    ]
  }
}

describe('Postman v2.1 round trip', () => {
  it('keeps the whole collection through export -> import', () => {
    const original = sample()
    const back = importPostmanCollection(exportPostmanCollection(original))
    expect(strip(back)).toEqual(strip(original))
  })

  it('survives non-ASCII, CRLF and large bodies', () => {
    const original = sample()
    const node = original.children[0] as CollectionFolderNode
    ;(node.children[0] as { request: RequestModel }).request.body = {
      type: 'raw',
      language: 'json',
      text: '{\r\n  "текст": "👋 ёлка",\r\n  "big": "' + 'x'.repeat(100000) + '"\r\n}'
    }
    const back = importPostmanCollection(exportPostmanCollection(original))
    expect(strip(back)).toEqual(strip(original))
  })

  it('does not crash on a malformed collection document', () => {
    expect(() => importPostmanCollection({ info: { name: 'x' }, item: [null, 5, 'str'] })).not.toThrow()
    expect(() => importPostmanCollection({ info: { name: 'x' }, item: { not: 'an array' } })).not.toThrow()
    expect(importPostmanCollection({}).children).toEqual([])
  })
})
